name: heart_lake
description: 心湖 - 社交最后一片净土
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  http: ^1.2.0
  http_parser: ^4.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.7
  fl_chart: ^0.69.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  audioplayers: ^6.1.0
  file_picker: ^8.0.0
  flutter_secure_storage: ^9.0.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
