#!/usr/bin/env bash

heartlake_rand_hex() {
    local bytes="${1:-16}"
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "${bytes}"
        return 0
    fi
    if command -v xxd >/dev/null 2>&1; then
        head -c "${bytes}" /dev/urandom | xxd -p -c 256
        return 0
    fi
    od -An -N"${bytes}" -tx1 /dev/urandom | tr -d ' \n'
}

heartlake_env_get() {
    local key="$1"
    local file="$2"
    awk -F= -v key="${key}" '$0 ~ ("^" key "=") {sub(/^[^=]+=/, ""); print; exit}' "${file}"
}

heartlake_env_upsert() {
    local key="$1"
    local value="$2"
    local file="$3"
    local tmp
    tmp="$(mktemp)"
    awk -v key="${key}" -v value="${value}" '
        BEGIN { updated = 0 }
        $0 ~ ("^" key "=") && updated == 0 {
            print key "=" value
            updated = 1
            next
        }
        { print }
        END {
            if (updated == 0) {
                print key "=" value
            }
        }
    ' "${file}" > "${tmp}"
    mv "${tmp}" "${file}"
}

heartlake_hash_admin_password() {
    local password="$1"
    local salt_hex="$2"

    if ! command -v openssl >/dev/null 2>&1; then
        echo "FATAL: openssl is required to bootstrap ADMIN_PASSWORD_HASH" >&2
        return 1
    fi

    openssl kdf -keylen 64 \
        -kdfopt digest:SHA256 \
        -kdfopt "pass:${password}" \
        -kdfopt "hexsalt:${salt_hex}" \
        -kdfopt iter:100000 \
        PBKDF2 | tr -d ':\n' | tr 'A-F' 'a-f'
}

heartlake_bootstrap_env() {
    local env_file="$1"
    local secrets_file="${2:-}"
    local context="${3:-HeartLake}"
    local generated_any=0
    local admin_password=""

    if [[ ! -f "${env_file}" ]]; then
        echo "FATAL: env file not found: ${env_file}" >&2
        return 1
    fi

    if [[ -z "$(heartlake_env_get "ADMIN_USERNAME" "${env_file}")" ]]; then
        heartlake_env_upsert "ADMIN_USERNAME" "admin" "${env_file}"
    fi

    if [[ -z "$(heartlake_env_get "DB_PASSWORD" "${env_file}")" ]]; then
        heartlake_env_upsert "DB_PASSWORD" "$(heartlake_rand_hex 16)" "${env_file}"
        generated_any=1
    fi

    if [[ -z "$(heartlake_env_get "REDIS_PASSWORD" "${env_file}")" ]]; then
        heartlake_env_upsert "REDIS_PASSWORD" "$(heartlake_rand_hex 16)" "${env_file}"
        generated_any=1
    fi

    if [[ -z "$(heartlake_env_get "PASETO_KEY" "${env_file}")" ]]; then
        heartlake_env_upsert "PASETO_KEY" "$(heartlake_rand_hex 32)" "${env_file}"
        generated_any=1
    fi

    if [[ -z "$(heartlake_env_get "ADMIN_PASETO_KEY" "${env_file}")" ]]; then
        heartlake_env_upsert "ADMIN_PASETO_KEY" "$(heartlake_rand_hex 32)" "${env_file}"
        generated_any=1
    fi

    if [[ -z "$(heartlake_env_get "ADMIN_PASSWORD_HASH" "${env_file}")" ]]; then
        local salt_hex password_hash
        admin_password="HeartLake-$(heartlake_rand_hex 6)"
        salt_hex="$(heartlake_rand_hex 32)"
        password_hash="$(heartlake_hash_admin_password "${admin_password}" "${salt_hex}")" || return 1
        heartlake_env_upsert "ADMIN_PASSWORD_HASH" "${salt_hex}:${password_hash}" "${env_file}"
        generated_any=1
    fi

    if (( generated_any == 1 )); then
        if [[ -n "${admin_password}" && -n "${secrets_file}" ]]; then
            mkdir -p "$(dirname "${secrets_file}")"
            umask 077
            cat > "${secrets_file}" <<EOF
# Auto-generated by ${context}
ENV_FILE=${env_file}
ADMIN_USERNAME=$(heartlake_env_get "ADMIN_USERNAME" "${env_file}")
ADMIN_PASSWORD=${admin_password}
EOF
            chmod 600 "${secrets_file}"
            printf 'Bootstrapped missing secrets in %s. Admin password stored at %s.\n' "${env_file}" "${secrets_file}"
        else
            printf 'Bootstrapped missing secrets in %s.\n' "${env_file}"
        fi
    fi
}
