#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

usage() {
  cat <<'EOF'
用法:
  ./scripts/generate-server-env.sh --host 121.41.195.165 --admin-password 'YourStrongPass'

可选参数:
  --host HOST            公网 IP 或域名
  --admin-user USER      管理员用户名，默认 admin
  --admin-password PASS  管理员密码；不传则交互输入
  --https                生成 https/wss 公网地址
  --output FILE          输出文件，默认 .env.server-lite
EOF
}

HOST=""
ADMIN_USER="admin"
ADMIN_PASSWORD=""
OUTPUT_FILE=".env.server-lite"
USE_HTTPS="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)
      HOST="${2:-}"
      shift 2
      ;;
    --admin-user)
      ADMIN_USER="${2:-}"
      shift 2
      ;;
    --admin-password)
      ADMIN_PASSWORD="${2:-}"
      shift 2
      ;;
    --https)
      USE_HTTPS="true"
      shift
      ;;
    --output)
      OUTPUT_FILE="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "未知参数: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${HOST}" ]]; then
  echo "缺少 --host 参数" >&2
  usage
  exit 1
fi

if [[ -z "${ADMIN_PASSWORD}" ]]; then
  read -r -s -p "输入管理员密码: " ADMIN_PASSWORD
  echo
fi

if [[ -z "${ADMIN_PASSWORD}" ]]; then
  echo "管理员密码不能为空" >&2
  exit 1
fi

SCHEME="http"
WS_SCHEME="ws"
if [[ "${USE_HTTPS}" == "true" ]]; then
  SCHEME="https"
  WS_SCHEME="wss"
fi

DB_PASSWORD="$(openssl rand -hex 16)"
REDIS_PASSWORD="$(openssl rand -hex 16)"
PASETO_KEY="$(openssl rand -hex 32)"
ADMIN_PASETO_KEY="$(openssl rand -hex 32)"
ADMIN_SALT="$(openssl rand -hex 32)"
ADMIN_HASH="$(
  openssl kdf -keylen 64 \
    -kdfopt digest:SHA256 \
    -kdfopt "pass:${ADMIN_PASSWORD}" \
    -kdfopt "hexsalt:${ADMIN_SALT}" \
    -kdfopt iter:100000 \
    PBKDF2 | tr -d ':\n' | tr 'A-F' 'a-f'
)"
ADMIN_PASSWORD_HASH="${ADMIN_SALT}:${ADMIN_HASH}"

cat > "${OUTPUT_FILE}" <<EOF
# Generated by scripts/generate-server-env.sh
DB_NAME=heartlake
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}

GATEWAY_BIND_HOST=0.0.0.0
GATEWAY_PORT=80
POSTGRES_BIND_HOST=127.0.0.1
POSTGRES_PORT=5432
REDIS_BIND_HOST=127.0.0.1
REDIS_PORT=6379
BACKEND_BIND_HOST=127.0.0.1
BACKEND_PORT=8080
ADMIN_BIND_HOST=127.0.0.1
ADMIN_PORT=5173

BACKEND_BUILD_JOBS=1
SERVER_THREADS=2
DB_POOL_SIZE=4
REDIS_POOL_SIZE=4
LOG_LEVEL=WARN

PUBLIC_API_URL=${SCHEME}://${HOST}/api
PUBLIC_WS_URL=${WS_SCHEME}://${HOST}/ws/broadcast
CORS_ALLOWED_ORIGIN=${SCHEME}://${HOST}

ADMIN_USERNAME=${ADMIN_USER}
ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}

PASETO_KEY=${PASETO_KEY}
ADMIN_PASETO_KEY=${ADMIN_PASETO_KEY}

AI_PROVIDER=ollama
AI_BASE_URL=http://127.0.0.1:11434
AI_MODEL=heartlake-qwen
AI_TIMEOUT=5

EMBEDDING_WARMUP_ON_BOOT=false
ENABLE_LAKE_GOD_GUARDIAN=false
ENABLE_EMOTION_TRACKING=false
ENABLE_USER_FOLLOWUP=false
ENABLE_WS_HEARTBEAT=true
REALTIME_QUIC_ENABLED=false
EOF

echo "已生成 ${OUTPUT_FILE}"
echo "管理员用户名: ${ADMIN_USER}"
echo "公网入口: ${SCHEME}://${HOST}"
echo "下一步: cp ${OUTPUT_FILE} .env && ./scripts/docker-up.sh server-lite"
